#!/bin/sh

#make distclean

#./configure --disable-encoders --disable-debug --enable-runtime-cpudetect --disable-pthreads --enable-static --enable-w32threads --enable-memalign-hack

# TODO: --enable-libschroedinger
# TODO: --enable-libx264 --extra-cflags=-I/local/x264/include --extra-ldflags=-L/local/x264/lib

# use this to build a GPL enabled version (better sw scaler performance, XVID codec (not required to decode xvid movies) and AMR support but the DLL can't be distributed)
# (mplayer-ww MinGW)
#./configure --disable-debug --disable-encoders --disable-devices --disable-protocols --enable-gpl --enable-version3 --enable-libvorbis --enable-libtheora --enable-libspeex --enable-libmp3lame --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-libvpx --disable-decoder=libvpx --enable-runtime-cpudetect --enable-libxvid --enable-avisynth --enable-w32threads --enable-memalign-hack --enable-static --disable-avfilter --disable-postproc
# (i686-w64-mingw32)
PKG_CONFIG_LIBDIR="${LGVID_DEP_PREFIX}/lib/pkgconfig" ./configure --disable-debug --disable-encoders --disable-devices --disable-protocols --enable-gpl --enable-version3 --enable-libvorbis --enable-libtheora --enable-libspeex --enable-libmp3lame --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-libvpx --disable-decoder=libvpx --enable-runtime-cpudetect --enable-libxvid --enable-avisynth --enable-pthreads --enable-memalign-hack --enable-static --disable-avfilter --disable-postproc --enable-cross-compile --cross-prefix=i686-w64-mingw32- --arch=i686 --target-os=mingw32 --extra-ldflags="-L/usr/i686-w64-mingw32/lib -L${LGVID_DEP_PREFIX}/lib -L./libavdevice -L./libavformat -L./libavcodec -L./libswscale -L./libavutil" --extra-cflags="-I/usr/i686-w64-mingw32/include -I${LGVID_DEP_PREFIX}/include"

# build LGPL version
# (mplayer-ww MinGW)
#./configure --disable-debug --disable-encoders --disable-devices --disable-protocols --enable-libvorbis --enable-libtheora --enable-libspeex --enable-libmp3lame --enable-libvpx --disable-decoder=libvpx --enable-runtime-cpudetect --enable-avisynth --enable-w32threads --enable-memalign-hack --enable-static --disable-avfilter --disable-postproc
# (i686-w64-mingw32)
#PKG_CONFIG_LIBDIR="${LVGID_DEP_PREFIX}/lib/pkgconfig" ./configure --disable-debug --disable-encoders --disable-devices --disable-protocols --enable-libvorbis --enable-libtheora --enable-libspeex --enable-libmp3lame --enable-libvpx --disable-decoder=libvpx --enable-runtime-cpudetect --enable-avisynth --enable-w32threads --enable-memalign-hack --enable-static --disable-avfilter --disable-postproc --enable-cross-compile --cross-prefix=i686-w64-mingw32- --arch=i686 --target-os=mingw32 --extra-ldflags="-L/usr/i686-w64-mingw32/lib -L${LGVID_DEP_PREFIX}/lib -L./libavdevice -L./libavformat -L./libavcodec -L./libswscale -L./libavutil" --extra-cflags="-I/usr/i686-w64-mingw32/include -I${LGVID_DEP_PREFIX}/include"
